---
name: Build - Windows and macOS
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ci_version:
        required: true
        type: string

jobs:
  build:
    env:
      CI_VERSION: ${{ inputs.ci_version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            qt_version: 6.7.0
            arch: win64_msvc2022_64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.arch }}

      - name: Debug - Check environment (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          qmake -v
          where qmake

      - name: Qmake (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          qmake moonlight-qt.pro -spec win32-msvc CONFIG+=release

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          nmake /NOLOGO

      - name: Upload Source Code (Windows)
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows' && always()
        with:
          name: GSLCloud-Windows-src-${{ env.CI_VERSION }}
          path: |
            app/gui/**
            app/backend/**
            app/settings/**
            *.pro
          if-no-files-found: warn

